### ISSUE TITLE
Junk character in output pdf

### ISSUE THREAD

**Issue by cchetan789** [andrewferrier/email2pdf#118]
Hi,
**I have processed the eml file and get the output with some junk characters.**
and how to resize the content in eml file as it get half cut due to its resolution and only half data is printed in pdf.
![Screenshot_20200801_164247](https://user-images.githubusercontent.com/39484651/89100612-0961e100-d416-11ea-857e-7f752b93d647.png)

Please let me know how to solve this problems.

Regards,
Chetan

**Comment by andrewferrier** [comment]
Chetan, you're going to need to supply more information, I'm afraid. Do you have the original email? Can you share it with me? (or a redacted version, for privacy?).
