### ISSUE TITLE
Decode email subject in header

### ISSUE THREAD

**Issue by ceear** [andrewferrier/email2pdf#74]
Hi,

international (non english) emails often have an encoded subject like :

=?iso-8859-1?Q?Hall=F6chen?=
=?UTF-8?Q?Hall=C3=B6chen?=
=?UTF-8?B?SGFsbMO2Y2hlbg==?=
=?iso-2022-jp?B?GyRCOiNHLyRiSSwkOiRkJGo/ayQyJGsbKEIhIRskQkcvS3ZBMCRO?=
=?GB2312?B?0rvSubzkyMM1MDDN8sjLudjXosT6svrGt7XEzfjC59Oq?=

There is an easy way to decode such headers in perl : 
echo '=?UTF-8?B?SGFsbMO2Y2hlbg==?=' | perl -MEncode -ne 'print encode("utf8",decode("MIME-Header",$_))'

Is there any way to implement such a function in your script  - which is btw awesome and exactly what i was looking for :-) ?

http://stackoverflow.com/questions/7331351/python-email-header-decoding-utf-8

Thanks
Chris

**Comment by andrewferrier** [comment]
Chris,

Thanks very much for your bug report. You're quite right, I wasn't handling subjects properly here. I think that's now fixed in d05aded - can you pull down the latest changes and retest for me please?

Thanks, Andrew.

**Comment by ceear** [comment]
Hi Andrew,

wow - thank you!

I've checked the new version with a few of the "problematic" emails.
Most of them are decoded very well now!

There is currently one email that will not convert:
RAW header : Subject: Ihre Anfrage, Giesestra=?utf-8?B?w58=?=e 5
(sorry - german)

Error:
Traceback (most recent call last):
  File "/opt/email2pdf/email2pdf-master/email2pdf", line 550, in call_main
    main(sys.argv, syslog_handler, syserr_handler)
  File "/opt/email2pdf/email2pdf-master/email2pdf", line 96, in main
    header_info = get_formatted_header_info(input_email)
  File "/opt/email2pdf/email2pdf-master/email2pdf", line 496, in get_formatted_header_info
    decoded_string = get_utf8_header(input_email[header])
  File "/opt/email2pdf/email2pdf-master/email2pdf", line 522, in get_utf8_header
    assert len(decoded_header) == 1
AssertionError


Another question: I'm not sure but i think its (RFC-) allowed to have multiple (different) encodings for the subject. Will your code handle such subjects?   


Thank you for your great support!
Chris

**Comment by andrewferrier** [comment]
Chris, OK, I'll test out that German one a little later and see if I can figure out what's happening. I think you're right - it is legal to have more than one encoding, and I don't think I'm handling that case (in fact, I'm specifically prohibiting it). Let me try that out a bit later too.

**Comment by andrewferrier** [comment]
OK, so I think I've fixed those remaining concerns as of commit 23f7f60 - email2pdf should now handle the German string you cited above correctly, as well as (more generally) headers with multiple encodings/parts to them, including parts with no explicit encoding.

Can you test this out again and make sure it works for you, please? Thanks again for your bug report and helping me make email2pdf more robust!

**Comment by ceear** [comment]
All the headers are handled fine now.

Thank you so much!
