### ISSUE TITLE
HTML specific characters will not be displayed in plain/text emails

### ISSUE THREAD

**Issue by gpgmailencrypt** [andrewferrier/email2pdf#93]
Hi,
if a plain text email contains e.g. a '<' character, this will be not displayed in the resulting pdf. Reason is, that it will be handled as the starting point of a tag and thus not be printed as a normal character. There are also some other characters having this problem. I recommend using html.escape() function in your handle_message_body function

Horst

**Comment by andrewferrier** [comment]
Great spot, thanks. I think I've fixed this now (as well as adding some unit tests to validate that).
